server:
  port: 8040

openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo-0613
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1/chat/completions
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

firefall-services:
  x-api-key: scoe-hackathon-app
  x-gw-ims-org-id: 154340995B76EEF60A494007@AdobeOrg
  access-token: eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEtc3RnMS1rZXktYXQtMS5jZXIiLCJraWQiOiJpbXNfbmExLXN0ZzEta2V5LWF0LTEiLCJpdHQiOiJhdCJ9.eyJpZCI6IjE2OTYzMTQ5NTIwNDVfNjYyNDk3NjUtMmIyNy00NzUyLThhZDQtNWM3N2QyODdhNDE5X2V3MSIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJjbGllbnRfaWQiOiJzY29lLWhhY2thdGhvbi1hcHAiLCJ1c2VyX2lkIjoic2NvZS1oYWNrYXRob24tYXBwQEFkb2JlSUQiLCJhcyI6Imltcy1uYTEtc3RnMSIsImFhX2lkIjoic2NvZS1oYWNrYXRob24tYXBwQEFkb2JlSUQiLCJjdHAiOjAsInBhYyI6InNjb2UtaGFja2F0aG9uLWFwcF9zdGciLCJydGlkIjoiMTY5NjMxNDk1MjA0Nl84Nzc2MjFhNy1lOTgzLTQ1ZTMtYTBiNS1mZWM2MWUwZjNmNzNfZXcxIiwibW9pIjoiOTYzYTZiN2UiLCJydGVhIjoiMTY5NzUyNDU1MjA0NiIsImV4cGlyZXNfaW4iOiI4NjQwMDAwMCIsInNjb3BlIjoic3lzdGVtIiwiY3JlYXRlZF9hdCI6IjE2OTYzMTQ5NTIwNDUifQ.d46vAmYDNpfOUF6gXKLH_801vO_5sz8_jFCg8CVp9bZQ-xa0JaFU3iaXCqf37WWiy0XuO8shfiVVRR3i9uFZouAS9cZ-fnzgWSx0wlls8T50NAwWcoBPPwU2_9NkdnEB3cDCeeYijhIutPPg-2owbXHU_hhJxMxErlnE7ICvtdfsD2d7sjZ-Mi3mxDIj2q7aiuP6mmUOh7DMh_ch0wLR4C9SV7qIQEP3nyn2QYFIqdOBiALHpZ0mt2_4N3kWLox25CSlgGXa3k02MHUZW7CyQs2cjjOXfwXaJd-glYLcFxWKm3aMZf4kO5R2lDHA4QpSMfFmJMvMJnQQm9gxVsYnbw
  completions-url: https://firefall-stage.adobe.io/v1/completions
  emerald-colleciton-search: https://emerald-stage.adobe.io/collection/firefall_adobe_acrobat_sign/search
  emerald-asset-search: https://emerald-stage.adobe.io/collection/firefall_adobe_acrobat_sign/asset/
  conversation: https://firefall-stage.adobe.io/v2/conversation/
  set-conversation: https://firefall-stage.adobe.io/v1/chat/completions/conversations
  statefull-completions: https://firefall-stage.adobe.io/v1/chat/completions
  llm:
    model_name: gpt-35-turbo
    temperature: 0.7
    max_tokens: 2000
    top_p: 0.95
    frequency_penalty: 0
    presence_penalty: 0
    llm_type: azure_chat_openai

logging:
  level:
    org: 
      hibernate:
        SQL: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/almsign
    username: postgres
    password: aabbhhii
  jpa:
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB        
  application:
    name: Doc Sign Application
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
integration-key: 3AAABLblqZhDC7cGLcDKeB7Fv4AwckDu586QhT0XtzhN4BMX173wLbkxVL1OxslyPrCbw0iMGe6XfV_x2Dx7319msMki7FejG
createContractPath: src/main/resources/contract/exitForm/index.zip
downloadPath: output/
baseUrl: https://api.in1.adobesign.com
#Enable visibility based on SHOW_VISIBLE or SHOW_HIDDEN or SHOW_ALL 
visibility: SHOW_ALL
pageSize: 50
agreement_status: SIGNED,CANCELLED,EXPIRED,ACCEPTED,APPROVED,DISABLED,OUT_FOR_SIGNATURE,ACTIVE
agreement_type: AGREEMENT, MEGASIGN_CHILD, WIDGET_INSTANCE, MEGASIGN_PARENT
user_role: SENDER,SIGNER,APPROVER,FORM_FILLER,ACCEPTOR,CERTIFIED_RECIPIENT,DELEGATE_TO_SIGNER,DELEGATE_TO_APPROVER,DELEGATE_TO_FORM_FILLER,DELEGATE_TO_ACCEPTOR,DELEGATE_TO_CERTIFIED_RECIPIENT
