server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB        
  application:
    name: Doc Sign Application
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
integration-key: 
createContractPath: src/main/resources/contract/exitForm/index.zip
downloadPath: output/
baseUrl: https://abhishekdixitg.in1.adobesign.com
agreement_status: SIGNED,CANCELLED,EXPIRED,ACCEPTED,APPROVED,DISABLED
agreement_type: AGREEMENT, MEGASIGN_CHILD, WIDGET_INSTANCE, MEGASIGN_PARENT
user_role: SENDER,SIGNER,APPROVER,FORM_FILLER,ACCEPTOR,CERTIFIED_RECIPIENT,DELEGATE_TO_SIGNER,DELEGATE_TO_APPROVER,DELEGATE_TO_FORM_FILLER,DELEGATE_TO_ACCEPTOR,DELEGATE_TO_CERTIFIED_RECIPIENT