# must be unique in a given SonarQube instance
sonar.projectKey=BulkOperationsTool
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=BulkOperationsTool
sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=src/main/java
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.java.source=1.8

sonar.exclusions=src/main/java/com/adobe/acrobatsign/DocsigningApplication.java, src/main/java/com/adobe/acrobatsign/service/RestApiAgreements.java.java, src/main/java/com/adobe/acrobatsign/model/**,src/main/java/com/adobe/acrobatsign/util/**

# Tests
sonar.tests=src/test
sonar.junit.reportPaths=target/surefire-reports
sonar.java.coveragePlugin=jacoco
sonar.junit.reportsPath=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.cobertura.reportPath=target/site/cobertura/coverage.xml
sonar.clover.reportPath=target/clover.xml
 
sonar.dynamicAnalysis=reuseReports
sonar.java.coveragePlugin=plugin   # either jacoco or cobertura or clover
sonar.scm.enabled=true
sonar.scm.provider=git