import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isAuthenticated: false,
    user: null,
};

const authReducer = createSlice({
    name: 'auth', 
    initialState,
    reducers: {
        login(state, action) {
            state.isAuthenticated = true;
            state.user = action.payload.user; 
        },
        logout(state) {
            state.isAuthenticated = false;
            state.user = null; 
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout } = authReducer.actions;

// Export the reducer as default
export default authReducer.reducer;