import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isAuthenticated: false,
    user: null,
    token: null,  // Add token to the initial state
};

const authReducer = createSlice({
    name: 'auth', 
    initialState,
    reducers: {
        login(state, action) {
            state.isAuthenticated = true;
            state.user = action.payload.user; 
            state.token = action.payload.token;  // Set token when logging in
        },
        logout(state) {
            state.isAuthenticated = false;
            state.user = null; 
            state.token = null;  // Clear token on logout
        },
    },
});

// Export the actions generated by createSlice
export const { login, logout } = authReducer.actions;

// Export the reducer as default
export default authReducer.reducer;
